bytebeamio/uplink

- disk/src/lib.rs
- uplink/src/base/actions/mod.rs
- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
- uplink/src/collector/systemstats.rs
- uplink/src/collector/tcpjson.rs
Remove calls to `unwrap()` and `expect()` and instead return Errors
> Error out instead of panic

- .github/workflows/release.yml
Closes #17 
Automatically creates a release when a tag with format `v*.*.*` is pushed on any branch (there is a workaround to make this run only for `main` branch but I don't think that complexity is worth adding) and uploads the binaries to it.
Test runs can be found here:
Release: https://github.com/henil/uplink-dev/releases/tag/v0.5.2
Workflow run: https://github.com/henil/uplink-dev/actions/runs/2494209226
> Update CI/CD 

- uplink/src/base/serializer.rs
Fix bugs and documentation in `Serializer` state-machine implementation.
- Write initial failed publish packet to disk in `crash()`.
- rename `disk()` to `slow()` and handle network publish error as `EventLoopCrash`
- Better document code
To ensure code works as expected.
These issues in code were discovered in #7
> Fix `Serializer` bugs and documentation

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/base/serializer.rs
Brings changes associated with new rumqttc version into uplink, including the following error log entry when trying to connect to the wrong port.
- 1-to-1 mapping between `ClientError` and `MqttError` variants
Error log now contains entry when unable to connect to broker due to improper port config.
```
******* [ERROR] (21) uplink::base::mqtt: Connection error = "Timeout"
```
To keep dependencies updated.
Checked operations against regular uplink instance. Similar behavior observed.
> update rumqttc to v0.14

- runit/uplink/run
@tekjar set `BROKER` env variable according to the environment in which it is to be run
> fix: runit new command

- uplink/src/collector/simulator.rs
`ActionResponse`s from simulator happened to be unnecessarily repackaged inside a `Payload`. This has been reworked by creating a separate map of streams for `action_status`es.
> fix: `ActionResponse` json generated in Simulator

- examples/demo.go
- examples/demo.py
Wrote apps that connect to the bridge port, receive `Action`s and respond back with an `ActionResponse` with `state: Completed`.
Add demo apps written in python and golang
To demonstrate the use of uplink with a connected application.
Ran against normal uplink instance connected to local broker, verified receiving bridge `Action` and response.
> feat: add demo go and python programs

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
- uplink/src/collector/tcpjson.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes BYT-496
Field to configure a stream's topic should be made optional to ensure the user doesn't have to deal with it when wanting to configure the buffer size.
> feat: make stream topic field optional

- configs/demo.toml
- configs/device_demo.json
- runit/uplink/run
Closes BYT-511
Currently runit uses the wrong configs for running uplink as demo simulator.
- Add `demo.toml` as uplink config
- Add `device_demo.json` as uplink auth
> fix: override configs for demo simulator

- uplink/src/base/serializer.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Serializer's `Metrics` currently doesn't construct a stream
Push serializer metrics data onto stream configured from user provided details.
Metrics is being sent as batch of size 1 even when configured otherwise.
Configured and sent over metrics data in batch of 10, data push frequency has significantly decreased
> feat: Streamize metrics

- uplink/src/base/serializer.rs
- uplink/src/lib.rs
Closes #
Forward serializer metrics only if metrics stream is configured
serializer metrics might be unnecessary for certain usecases and hence leaving it unconfigured should cause the serializer to stop sending this information to the platform.
> feat: optionalize serializer metrics

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/lib.rs
Closes #
Rework config to allow for special cases `serializer_metrics` and `action_status`
Require configuration for `serializer_metrics` and `action_status` to be separate from `streams`
Allows for consistent configuration of special streams
> feat: rework config

- uplink/src/base/actions/ota.rs
Closes #
Currently server errors are being written to file even though they should be reported as failures to platform
Server errors on reqwest reported to platform
> fix: Forward server errors as `ActionResponse`

- uplink/src/lib.rs
Closes #
journalctl is left disabled by default. To enable, add the following to `config.yaml`:
```
[journalctl]
tags = ["kernel"]
priority = 6
```
This is expected behaviour
regular usage
> fix: disable journalctl by default

- uplink/src/base/actions/mod.rs
- uplink/src/base/mod.rs
- uplink/src/collector/tcpjson.rs
- uplink/src/lib.rs
Closes #
Current `ActionResponse` parsing from `Payload` is faulty, and can fail on use of `"id"` as key instead of `"action_id"`, which should be allowed.
`ActionResponse` <=> `Payload`
For use when checking `CurrentAction`
> fix: `ActionResponse` from `Payload`

- README.md
- configs/config.toml
- examples/demo.py
- tools/actions/main.go
- uplink/src/base/middleware/mod.rs
- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/collector/mod.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Rename and generalize working of `OtaDownloader`
Allow user to customize downloader and allow triggering file downloads for multiple types of actions as follows:
```
[downloader]
actions = ["firmware_update", "send_file"]
path = "/path/to/downloads"
```
This will simplify the download feature and enable downloads for non-OTA tasks as well.
> feat: refactor as `FileDownloader` to handle non OTA actions

- uplink/src/collector/logging/journalctl.rs
- uplink/src/collector/logging/logcat.rs
- uplink/src/collector/logging/mod.rs
Closes #
Convert `log_timestamp` value collected by journalctl into millis from micros
Platform expects millis
> fix: parse timestamp for journalctl log entries into millis

- README.md
- configs/config.toml
- docs/apps.md
Closes #
"firmware_update" ~> "update_firmware" in example configs and docs
The platform sends actions with name "update_firmware", not "firmware_update"
> doc: fix action name for OTA

- examples/demo.go
- examples/demo.py
- tools/actions/main.go
- tools/update_firmware.go
- uplink/src/base/actions.rs
Closes #
Use `action_id` instead of `id` as field for "action_status" in examples, allow old code to continue working by aliasing it as `id`.
This updates the documentary code to support changes made by @bmcpt in #72 and ensures applications written with older uplink in mind aren't broken in the process.  
Run against examples with and without the change, both are observed to be working as expected.
> fix: use `action_id` and let it alias as `id` for "action_status"

- uplink/src/base/mod.rs
- uplink/src/bin/test.rs
- uplink/src/collector/tcpjson.rs
Added `ignore_actions_if_client_disconnected` boolean flag to config. Works as name suggests.
Actions received between uplink start and client connect are failed needlessly.
> Add 'ignore_actions_if_no_clients'

- uplink/src/lib.rs
Closes #
Removes the config that enforced default mode of uplink persisting to disk, this should remain an optional feature.
Users may want to run uplink without persisting to disk.
> fix: default to no persistence

- uplink/src/base/mod.rs
- uplink/src/base/mqtt.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #EXP-116
Enables config of rumqttc's `keep_alive` value, while defaulting to 60s.
Users may want to config this according to custom requirements.
> feat: make `keep_alive` configurable

- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
Closes #
This can be helpful to keep track of the number of messages overall handled through a specific stream.
For better observability into the data pipeline
> feat: let `Serializer` query `Package`s batch size

- uplink/src/base/actions.rs
- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
- uplink/src/collector/logging/journalctl.rs
- uplink/src/collector/simulator.rs
- uplink/src/collector/systemstats.rs
- uplink/src/collector/tcpjson.rs
Closes #
Adds the methods `collection_timestamp` to `Point` and `first_timestamp`, `last_timestamp`, `batch_latency` to `Package`. Log batch latency from within `Serializer`
> feat: collect and log `batching_latency` as a metric

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
- uplink/src/lib.rs
Closes #
Push serializer metrics directly to broker instead of through `Stream`
If we are to follow the current way of doing things, we will end up collecting stats generated by the stats themselves, this would lead to a snake eating its tail kind of situation which we should avoid.
Tested against platform, metrics generated seems to add up.
> fix: serializer metrics ouroboros

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
- uplink/src/base/serializer/metrics.rs
- uplink/src/lib.rs
Closes #
Adds handler to keep track of per stream metrics.
Enables monitoring of uplink working at a per-stream level.
Run against main_app sending `device_shadow` with differing `buf_sizes`
1. when set to buf size 1, i.e. direct flush, json looks like
```
[
{
"timestamp": 1672339700764,
"sequence": 4,
"stream: "device_shadow",
"point_count": 7,
"batch_count": 7,
"average_latency": 0.0,
"min_latency": 0,
"max_latency": 0
}
]
```
2. 10 points, with slightly large latencies(~45s according to the following):
```
[
{
"timestamp": 1672340100612,
"sequence": 1,
"stream": "device_shadow",
"point_count": 10,
"batch_count": 1,
"average_latency": 45046.0,
"min_latency": 45046,
"max_latency": 45046
}
]
```
> feat: collect and forward `stream_metrics`

- docs/apps.md
- uplink/src/base/middleware/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/collector/tcpjson.rs
Closes #
Enable multiple collectors, broadcasting actions as received, to all connected applications.
- Accept multiple TCP connections
- Broadcast actions to all connected applications, let the application choose if they want to process the received action or not
NOTE: `current_action` still limits how many actions we can process at a time, so if an action was broadcast to all connected apps, uplink will not broadcast the next action until the action being processed times out or returns a `"Completed"/"Failed"` status.
Users might want to connect multiple applications to a single uplink instance, with the same TCP port/bridge.
1. Multiple applications are able to connect and send data, while also being able to receive the same action as each other.
2. When no application is connected, …
> feat: multiple tcp collectors, broadcast actions

- uplink/src/base/serializer.rs
- uplink/src/base/serializer/metrics.rs
Closes #
Clears/flushes stream metrics from the map on writing to network. 
It is required that we keep track of stats only until they are written to network
> fix: clear `stream_metrics` on write to network

- uplink/src/base/mod.rs
Closes #94
Use default values for missing persistence configs
Allows backward compatibility with certain config files
> fix: set default values for persistence config if missing

- uplink/src/base/mod.rs
- uplink/src/base/serializer/metrics.rs
- uplink/src/lib.rs
Closes #
Enables blacklisting streams that shouldn't be tracked for uplink stats
Users may want to keep certain streams from having their metrics information tracked
> feat: add onfigurable blacklist to `stream_metrics`

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/serializer/metrics.rs
- uplink/src/collector/util.rs
- uplink/src/lib.rs
Closes #
Adds a new field that allows users to configure certain streams, allowing them to bypass the metrics collector, instead of per metrics config black listing.
Currently configuration has to be made for each collector, the PR allows a global configuration that bypasses the stream from metrics collectors.
> feat: global config to bypass uplink metrics collectors

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/collector/logging/logcat.rs
Closes #
Use time instead of chrono and add dependencies specific to android targets
For compilation to android targets
> fix: compilation for android targets

- .github/workflows/rust.yml
Closes #
- Removes build step from CI runs on each PR
- Adds clippy run with aarch64-android target for confirming android compatibility of PR
Helps to maintain compatibility of codebase with android targets, using aarch64 alone for compute and wait reasons.
> clippy for android

- configs/config.toml
- uplink/src/base/bridge/bridge.rs
- uplink/src/base/mod.rs
- uplink/src/collector/tcpjson.rs
- uplink/src/main.rs
Closes #
The user configuring uplink to work with their app will have a clear understanding of their requirements, i.e. what all applications will be connecting to uplink, before hand and will hence configure uplink appropriately, thus reducing the heavy lifting from within uplink and significantly improving the quality of life for developers and us maintainers 🥇 
Used against multiple demo apps connecting to separate ports, no two apps could connect to the same port together as the other blocks it. Apps received actions that had the app's name mentioned in them.
**Issue noticed that needs resolution in separate PR:** actions could not be forwarded to a connected app if there were multiple apps and one had received an action and had not finished processing it yet(i.e. `state` values of …
> feat: multiple tcp ports, one per app re-design

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/lib.rs
Closes #
- Rename actions to processes
- use `DownloaderConfig` to route actions meant for file download
Trigger appropriate download file and process actions from platform
> fix: proper use of configurations for process and downloader apps

- tools/utils/Cargo.lock
- uplink/src/collector/tcpjson.rs
Allow multiple clients to respond to an action. Send bridge disconnected status only when all clients disconnect.
OTA in reactlabs setup consists of multiple steps which are handled by multiple clients.
> Multiple action processors

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/mqtt/mod.rs
- uplink/src/base/serializer/serializer.rs
- uplink/src/collector/downloader.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Nest the configs for MQTT client, i.e. `max_packet_size`, `max_inflight` and `keep_alive` within `Config.mqtt`
Used changed `config.toml` to test working of uplink initialization step, as expected proper config values were extracted from the config file and this was verified with a `dbg!(&config)`.
> feat: nest config for mqtt client

- uplink/src/base/mod.rs
Closes #
Default to disabled when config is missing
HTTP handler must be ideally disabled by default and only if configured to be so, should it be enabled
Run against `simulator.toml` which doesn't configure the apis field, observed to not throw the following error anymore:
```
Error: missing field `apis`
```
> fix: set `Config.apis.enabled = false` by default

- simulator.sh
Closes #
Run `simulator.sh` to create 20 devices with `./simulator.sh start_devices 20`, observed to work as expected, i.e. 20 uplinks created with appropriate configs. Used `./simulator.sh kill_devices` to kill the 20 devices created earlier, all devices stopped as expected.
> feat: improve `simulator.sh` cli messaging

- uplink/src/lib.rs
Closes #
Add missing level with the word "events" to properly resolve stream as expected by the data pipeline.
The stream topics for device shadow and uplink system stats in `DEFAULT_CONFIG` are missing a level with the word `events`, leading to data being lost in the pipeline.
Run against stage, data is received in appropriate stream when used without changing topic in config with toml
> fix: default stream topics

- uplink/src/collector/downloader.rs
Closes #
Currently file downloader sends action responses with wonky progress values when the download server doesn't provide file size in HTTP response. To fix this, the PR uses a counter called progress which keeps incrementing progress till 99, only setting it to 100 on completion. This means that progress could remain in the 10s if the file isn't large enough and the downloader doesn't have the info of file size expected.
Downloading file of size 35MB, response's progress shows following values in log:
```
response.progress = 2
response.progress = 3
response.progress = 4
response.progress = 5
response.progress = 6
response.progress = 7
response.progress = 8
response.progress = 9
response.progress = 10
response.progress = 11
response.progress = 12
response.progress = 13 …
```
> fix: maintain progress in case file size unknown

- uplink/src/collector/downloader.rs
Closes #
Store file with `file_name` instead of `artifact`.
Files are provided from platform under the name artifact while they should be instead stored with the `file_name` defined in received action.
Action created on platform to `send_file`, uplink configured with file downloader, observed the file to download at the appropriate path in fs: `{download_path}/{action_name}/{file_name}` instead of `{download_path}/{action_name}/{file_name}/artifact`.
unit testing of download action
> fix: store downloaded file with `file_name`

- simulator.sh
Closes #
Make changes to config generation code in `simulator.sh` necessary to allow it to run against new uplink.
Receive a "update_firmware" action, uplink observed to have run downloader as expected and then action redirection forwards the action to TCP port that accepts "install_firmware" actions and is running simulator code, which then continuously sends mock installation action statuses:
```
[2m2023-03-07T08:34:16.957969Z[0m [32m INFO[0m [1;32muplink::base::mqtt[0m[32m: [32mAction = Action { device_id: None, action_id: "5369", kind: "process", name: "update_firmware", payload: "{\"content-length\":223,\"status\":false,\"url\":\"https://firmware.cloud.bytebeam.io/api/v1/firmwares/v3.0.1/artifact\",\"version\":\"v3.0.1\"}" }[0m
[2m2023-03-07T08:34:16.958071Z[0m [32m …
```
> fix: action definition in sim config generator

- simulator.sh
Closes #
Add missing demo actions for use with simulator
Handle all actions from demo, i.e. "send_file", "update_firmware", "update_config", "unlock", "lock"
Used against stage simulator and triggered actions for "update_config", "unlock", "lock" it was observed that actions were run successfully on uplink and actions were updated on platform as such:
```
[2m2023-03-07T15:20:17.919897Z[0m [32m INFO[0m [1;32muplink::base::mqtt[0m[32m: [32mAction = Action { device_id: None, action_id: "127", kind: "process", name: "update_config", payload: "{\"name\":\"greeting\",\"version\":\"v1.1\",\"message\":\"Hello, World!\"}" }[0m
[2m2023-03-07T15:20:17.920064Z[0m [32m INFO[0m [1;32muplink::base::bridge[0m[32m: [32mReceived action: Action { device_id: None, action_id: "127", kind: …
```
> feat: handle all demo actions with simulator

- .gitignore
- uplink/src/collector/systemstats.rs
Closes #
Use process command line instead of process name if possible
process name is trimmed to last 16 characters.
> fix: use process.cmd[0] if available instead of process.name

- uplink/src/base/bridge/mod.rs
Closes #
Action handlers that don't send complete response but end with progress at 100 could be part of multi-stage actions, but if they have no redirections configured, uplink should send the completion response.
> feat: complete actions with no redirection

- tools/simulator/Cargo.lock
- tools/simulator/src/main.rs
Closes #
Output version numbers: ["v0.0.1", "v0.5.0", "v1.0.1"] instead of just ["on", "off"]
Run on simulator
> feat: `VerString` choose from version names

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/collector/installer.rs
- uplink/src/collector/mod.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Adds an built-in application installer that runs and disowns a shell script which connects back to uplink over tcp
To enable application updates without customer having to write their own handler
tar the following `update.sh`:
```sh
#!/bin/bash
ACTION_ID=$1
PORT=$2
echo "Received action{$ACTION_ID}, updating status with uplink on localhost:$PORT"
coproc nc localhost $PORT
echo "{ \"stream\": \"action_status\", \"sequence\": 0, \"timestamp\": $(date +%s%3N), \"action_id\": \"$ACTION_ID\", \"state\": \"Installing\", \"progress\": 0, \"errors\": [] }" >&"${COPROC[1]}"
sleep 5
echo "{ \"stream\": \"action_status\", \"sequence\": 0, \"timestamp\": $(date +%s%3N), \"action_id\": \"$ACTION_ID\", \"state\": \"Completed\", \"progress\": 100, \"errors\": [] }" >&"${COPROC[1]}"
```
```sh …
```
> feat: implement `OTAInstaller`

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/apis.rs
Closes #
```
curl -H "Content-Type: text/plain" -d "uplink=debug" http://0.0.0.0:3030/logs
curl -H "Content-Type: text/plain" -d "uplink=trace" http://0.0.0.0:3030/logs
curl -H "Content-Type: text/plain" -d "uplink=error" http://0.0.0.0:3030/logs
```
For understandable reasons, loglevels can't be improved, i.e. ERROR to DEBUG, if the loglevel set at the starting limits the loglevel to anything above DEBUG, e.g. INFO, which only allows improving the loglevel upto INFO.
> feat: use axum instead of rouille

- uplink/src/base/bridge/mod.rs
Closes #
Changes action router buffer size from 0 to 1, so that an incoming action is buffered for \<action timeout\> seconds if no client is connected.
> wait for clients in action routes buffer

- uplink/src/collector/downloader.rs
Closes #199 
Run against "send_file" and "update_firmware" actions from platform, it has been observed that files downloaded by previous actions don't get deleted if they don't have the same `file_name`. If a file with the same name exists on path, it is replaced by the new file, if there is a directory, it is deleted along with all it's contents and replaced with the file, if there exists nothing, the file and all its parent directories are created by the downloader.
Actions that contain empty `file_name` and `content_length == 0` are both notified to the platform appropriately as well, which was confirmed with a custom actions generator as it is not possible to reproduce on platform.
> fix: don't remove files, improve downloader error

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/mqtt/mod.rs
Closes #
Use toxy proxy to slowdown connection, triggering timeout in 30s, timeout is observed.
```
[uplink/src/base/mqtt/mod.rs:88] Instant::now() = Instant {
tv_sec: 42238,
tv_nsec: 563240499,
}
[uplink/src/base/mqtt/mod.rs:141] start.elapsed() = 30.002141581s
2023-04-04T13:35:26.598569Z ERROR uplink::base::mqtt:                        disconnected: reconnects = 1   publishes = 0   pubacks = 0   pingreqs = 0   pingresps = 0 
```
> feat: `network_timeout` in config

- simulator.sh
Closes #
The simulator currently stores the pid of all uplinks running in the same pids file, which leads to all uplinks getting evicted when the kill_device command is used, instead with this change we can target the exact uplink instance we want to kill.
> feat: enable targetted termination

- uplink/src/base/serializer/metrics.rs
- uplink/src/base/serializer/mod.rs
Closes #
- Make functions private and remove if unused
- Reorganize `Serializer` code documentation
- Explain `SerializerMetrics` in detail
- Remove use of `MqttClient::publish_bytes` as it is equivalent to `MqttClient::publish`
- Explain `MqttClient`
> feat: serializer module code improvements

- uplink/src/collector/logging/mod.rs
- uplink/src/lib.rs
Closes #
- Send success response on `logging_config` action completion
- Use bridge to forward logger data
- Configuration of uplink logger should manipulate logger
uplink's built-in logger doesn't respond with a success notification, nor does it use the bridge to send it's updates, both of which are wrong behavior and needs to be changed,
Sent an action from platform to start forwarding systemd logs, it replied back with a success. Uplink was configured with following config: 
```
[logging]
tags = []
min_level = 0
stream_size = 10
```
```
2023-04-19T09:55:21.270009Z TRACE uplink::base::bridge::stream: Flushing stream name: logs, topic: /tenants/demo/devices/615/events/logs/jsonarray
2023-04-19T09:55:21.270040Z TRACE uplink::base::serializer: Data received on stream: logs; message count = …
```
> fix: uplink logger success response, use bridge, stream config

- configs/config.toml
- uplink/src/base/bridge/mod.rs
- uplink/src/base/bridge/stream.rs
- uplink/src/base/mod.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/lib.rs
Closes #
Compression can be opted between "Lz4" and "Disabled" right now, where Disabled is the default option
The user should be able to choose if compression should be used on a particular stream or not
1. Start uplink with following config
```
[streams.imu]
topic = "/tenants/{tenant_id}/devices/{device_id}/events/imu/jsonarray"
buf_size = 100
compression = "Lz4"
```
2. Attach simulator generating data on multiple streams, including imu
<details>
<summary>uplink logs</summary>
<pre>
```
[2m2023-04-21T18:59:44.714330Z[0m [34mDEBUG[0m [1;34muplink::base::mqtt[0m[34m: [34mIncoming = PubAck(PubAck { pkid: 12 })[0m
[2m2023-04-21T18:59:44.776613Z[0m [34mDEBUG[0m [1;34muplink::base::serializer[0m[34m: [34mpublishing on /tenants/demo/devices/615/events/imu/jsonarray/lz4 with …
```
> feat: allow configuring compressibility per-stream

- uplink/src/base/mqtt/mod.rs
Closes #
Log error message on disconnection
Run uplink with json pointing to in-existent broker
```
2023-04-26T09:24:33.909442Z ERROR uplink::base::mqtt: disconnected I/O: Connection refused (os error 111): reconnects = 1   publishes = 0   pubacks = 0   pingreqs = 0   pingresps = 0  
2023-04-26T09:24:36.911179Z ERROR uplink::base::mqtt: disconnected I/O: Connection refused (os error 111): reconnects = 2   publishes = 0   pubacks = 0   pingreqs = 0   pingresps = 0  
2023-04-26T09:24:39.913571Z ERROR uplink::base::mqtt: disconnected I/O: Connection refused (os error 111): reconnects = 3   publishes = 0   pubacks = 0   pingreqs = 0   pingresps = 0 
```
Trying to connect to an HTTP server:
```
2023-04-26T09:25:46.812789Z ERROR uplink::base::mqtt: disconnected TLS: I/O: received corrupt …
```
> feat: add error trace

- uplink/src/base/mod.rs
- uplink/src/collector/installer.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Not all users want to trigger ota_installer when a firmware update completes downloading, keep this feature opt-in and clean-up DEFAULT_CONFIG
> fix: optionalize installer

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/base/bridge/mod.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Add the ability to trigger uplink shutdown, i.e. persisting current action on detecting a SIGTERM
Trigger shutdown with SIGINT/SIGTERM during action run on uplink
```
^C  2023-04-29T13:33:33.124109Z  INFO uplink::base::bridge: Storing current action in persistence; path: /tmp/uplink/current_action
2023-04-29T13:33:33.124246Z  INFO uplink: Uplink shutting down
```
restart uplink once it has stopped:
```
2023-04-29T13:34:55.805410Z  INFO uplink::base::bridge: Loading saved action from persistence; action_id: 389
```
> feat: trigger shutdown procedures on sigterm

- uplink/src/base/bridge/mod.rs
Closes #
An action that comes in while another is being processed
1. Trigger Action 1 from platform.
2. Ensure Action 1 runs on uplink and isn't compete/timedout during the run of this experiment, i.e. set timeout to be large and ensure handler doesn't send completion response.
3. Trigger Action 2 from platform. Failure response received on platform, but action responses from Action 1 aren't dropped anymore.
```   2023-04-29T13:54:08.290683Z  INFO uplink::base::bridge: Action response = ActionResponse { action_id: "391", device_id: None, sequence: 6, timestamp: 1682776448290, state: "Downloading", progress: 5, errors: [], done_response: None }
2023-04-29T13:54:08.290843Z DEBUG uplink::base::serializer: publishing on /tenants/demo/devices/615/action/status with size = 107 …
```
> fix: clear current action only if it triggered error

- uplink/src/main.rs
Closes #
Fixes the tracing filter created from the provided
currently the filter is being set wrongly(missing level for certain modules):
```
$ cargo run -- -c configs/config.toml -a configs/noauth.json -v -m uplink -m rumqttc
Compiling uplink v2.1.0 (/home/devdutt/bytebeam/uplink/uplink)
Finished dev [optimized + debuginfo] target(s) in 2.29s
Running `target/debug/uplink -c configs/config.toml -a configs/noauth.json -v -m uplink -m rumqttc`
[uplink/src/main.rs:44] levels = "uplink=info,rumqttc"
```
```
$ cargo run -- -c configs/config.toml -a configs/noauth.json -v
Compiling uplink v2.1.0 (/home/devdutt/bytebeam/uplink/uplink)
Finished dev [optimized + debuginfo] target(s) in 2.16s
Running `target/debug/uplink -c configs/config.toml -a configs/noauth.json -v`
[uplink/src/main.rs:44] …
```
> fix: tracing filter

- configs/config.toml
- uplink/src/base/serializer/mod.rs
Closes #
Do not change topic onto which data is to be pushed to broker, users to ensure config contains necessary suffixes
Using `config.toml` with uplink:
```
2023-05-10T15:36:46.310382Z DEBUG uplink::base::serializer: publishing on /tenants/demo/devices/615/events/imu/jsonarray/lz4 with size = 17866
```
Confirmed presence of data in clickhouse from dashboard
> fix: use compressed stream topic as is from config

- storage/src/lib.rs
- tools/deserialize-backup/Cargo.lock
- tools/deserialize-backup/Cargo.toml
- tools/deserialize-backup/src/main.rs
Closes #
Run uplink with certain streams having persistence to disk turned on. Ensuring backlog gets written to disk  because of network issues, disconnect uplink and run the utility on the backlog files:
```
╭─────────────┬──────────────────────┬──────────────────┬───────┬──────────────┬───────────┬───────────────────┬───────────┬────────────────────────┬──────────────────────┬───────────────┬──────────────╮
│ stream_name │ serialization_format │ compression_algo │ count │ message_rate │ data_size │ uncompressed_size │ data_rate │ uncompressed_data_rate │ start_timestamp      │ end_timestamp │ milliseconds │
├─────────────┼──────────────────────┼──────────────────┼───────┼──────────────┼───────────┼───────────────────┼───────────┼────────────────────────┼──────────────────────┼─────────── …
```
> fix: update backup-deserializer to support uplink v2.3

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/base/serializer/mod.rs
Closes #
1. Move `persistence_path` config to global level.
2. Rewrite persistence to disk to be enabled only when `max_file_count > 0` where 0 is default value.
i.e. requires config to contain the following to enable on-disk persistence:
```
[streams.{stream_name}]
...
persistence = { max_file_count = 10 } # enables on-disk persistence with max-file-count being 10, max_file_size is default value, 100MB. Path is taken from global value or default "/var/lib/uplink"
```
Ease of config for user
Run uplink with updated config.toml and verify write to disk on network disconnect for streams motor and gps. Ensure data is written onto network on reconnection.
```
INFO uplink::base::serializer:              slow: batches = 1530 errors = 0 lost = 2 disk_files = 4   write_memory = 8.58 MB …
```
> feat: global uplink `persistence_path` in config

- configs/config.toml
- uplink/src/collector/journalctl.rs
Closes #
```
[logging]
units = ["wpa_supplicant"]
min_level = 7
stream_size = 1
```
```
2023-05-06T08:34:28.256328Z TRACE uplink::base::serializer: Data received on stream: logs; message count = 1; batching latency = 0
2023-05-06T08:34:28.256365Z DEBUG uplink::base::serializer: publishing on /tenants/demo/devices/615/events/logs/jsonarray with size = 1343
2023-05-06T08:34:28.256482Z TRACE uplink::base::serializer: Data received on stream: logs; message count = 1; batching latency = 0
2023-05-06T08:34:28.256489Z DEBUG uplink::base::serializer: publishing on /tenants/demo/devices/615/events/logs/jsonarray with size = 1323
2023-05-06T08:34:28.256779Z TRACE uplink::base::serializer: Data received on stream: logs; message count = 1; batching latency = 0
2023-05-06T08:34:28.256806Z DEBUG …
```
> feat: log processes by unit name in journalctl

- Cargo.lock
- configs/config.toml
- uplink/Cargo.toml
- uplink/src/base/mod.rs
- uplink/src/collector/device_shadow.rs
- uplink/src/collector/mod.rs
- uplink/src/lib.rs
Closes #
An in-built collector to push device shadow with ping latency and uplink version information has been a requirement for a while now.
Create table on clickhouse:
```
CREATE TABLE demo.device_shadow
(
`id` String,
`date` Date DEFAULT toDate(timestamp),
`insert_timestamp` DateTime64(3) DEFAULT now64(),
`timestamp` DateTime64(3),
`sequence` UInt32,
`Status` Nullable(String),
`mode` Nullable(String),
`firmware_version` Nullable(String),
`config_version` Nullable(String),
`distance_travelled` Nullable(Int64),
`range` Nullable(Int64),
`SOC` Nullable(Float64),
`uplink_version` Nullable(String),
`latency` Nullable(UInt64)
)
ENGINE = MergeTree
PARTITION BY date
ORDER BY id
SETTINGS index_granularity = 8192
```
NOTE: All we care about are `uplink_version` and `latency`.
With uplink running …
> feat: collector to push ping latency updates on `device_shadow` stream

- uplink/src/collector/installer.rs
Closes #
Currently installer assumes presence of bash in the path which isn't guaranteed.
Assume the presence of an executable `updater` at the root of ota tarball and execute it. It can be a shell script with hashbang set to whatever is appropriate for the system.
Presence of bash in the path which isn't guaranteed.
Tested on linux and android devices.
> Generic installer

- uplink/src/base/bridge/mod.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
`create_dir_all` in initialization code ensures failure happens before uplink starts operation.
```
2023-06-07T07:42:37.707400Z  INFO uplink::base::bridge: Action response = ActionResponse { action_id: "739", device_id: None, sequence: 1, timestamp: 1686123757707, state: "Downloading", progress: 0, errors: [], done_response: None }
2023-06-07T07:42:37.707405Z TRACE uplink::base::bridge::stream: Flushing stream name: action_status, topic: /tenants/demo/devices/1001/action/status
2023-06-07T07:42:37.707566Z TRACE uplink::base::serializer: Data received on stream: action_status; message count = 1; batching latency = 0
2023-06-07T07:42:37.707602Z DEBUG uplink::base::serializer: publishing on /tenants/demo/devices/1001/action/status with size = 104
2023-06-07T07:42:37.707619Z TRACE …
```
> fix: bridge failure to shutdown on file permission denied

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/base/mod.rs
- uplink/src/lib.rs
- uplink/src/prometheus.rs
Closes #
Required prometheus metrics collector that parses text serialized format into JSON, pushes onto platform appropriate stream
Run uplink with following config values included:
```
[prometheus]
endpoint = "http://localhost:9090/metrics"
stream_name = "prometheus_metrics"
interval = 5
[streams.prometheus_metrics]
topic = "/tenants/{tenant_id}/devices/{device_id}/events/prometheus_metrics/jsonarray"
buf_size = 1
```
Observation: It can be observed that we are receiving the collected values as JSON at appropriate interval on beamd.
> feat: prometheus collector

- uplink/src/base/bridge/mod.rs
- uplink/src/base/bridge/streams.rs
- uplink/src/main.rs
Closes #
Flush all streams in bridge to ensure data is not lost during shutdown.
Data in streams that are not flushed get dropped on uplink shutdown.
Run uplink and trigger shutdown after some time:
```
^C  2023-06-23T11:54:18.245006Z  INFO uplink::base::bridge::streams: Flushed stream = uplink_disk_stats
2023-06-23T11:54:18.245066Z  INFO uplink::base::bridge::streams: Flushed stream = logs
2023-06-23T11:54:18.245075Z  INFO uplink::base::bridge::streams: Flushed stream = uplink_system_stats
2023-06-23T11:54:18.245082Z  INFO uplink::base::bridge::streams: Flushed stream = uplink_network_stats
2023-06-23T11:54:18.245088Z  INFO uplink::base::bridge::streams: Flushed stream = uplink_component_stats
2023-06-23T11:54:18.245094Z  INFO uplink::base::bridge::streams: Flushed stream = …
```
> feat: force flush all streams before shutdown

- configs/config.toml
- uplink/src/base/mod.rs
- uplink/src/lib.rs
Closes #
User apps may handle actions such that status messages are very frequent, the same in the case of `device_shadow` stream, thus `buf_size` is not a sensible requirement as anyways the receiver on the other side can handle the buffered data points as long as they are flushed as frequently as necessary, 5s per device shadow and 2s for action status.
Case 1: Generate 50 `action_status` messages in 2 seconds and 10 `device_shadow` data points in 5 seconds with simulator, ensure that they are batched with buffers of suitable size and within the expected time-period of 2s and 5s appropriately.
```
2023-07-14T09:44:27.631118Z TRACE uplink::base::bridge::streams: Initialized stream buffer for device_shadow
2023-07-14T09:44:32.633564Z TRACE uplink::base::serializer: Data received on …
```
> fix: use `flush_period` instead of `buf_size` for important streams

- uplink/src/base/bridge/mod.rs
Closes #
Uplink should ignore any failures during shutdown.
Right now save_current_action fails if `persistence_path` is wrong, causing uplink to ignore pkill.
> Uplink should ignore `save_current_action` failures

- uplink/src/base/bridge/mod.rs
- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
Closes #
1. Timeout downloads at expected timeout of action on bridge
2. Don't clear action on unsuccessful re-send even if with same id
Downloader as of right now continues to run despite the action having timedout on bridge, leading to further action failures as download actions clog the channel into the downloader
1. Create http server accessible over toxiproxy.
```
echo '#!/bin.sh' > test.sh
echo 'echo "Hello, World!"' >> test.sh
python3 -m http.server 8000
```
```
curl --request POST \
--url http://localhost:8474/proxies \
--header 'Content-Type: application/json' \
--data '{
"name": "script-server",
"listen": "0.0.0.0:8001",
"upstream": "localhost:8000",
"enabled": true
}'
```
3. Start uplink without auth.
```
{
"project_id": "demo",
"broker": "localhost",
"port": 1883, …
```
> fix: stop download on action timeout, don't drop action on resend

- uplink/src/collector/systemstats.rs
Closes #
- Separate out updater and directly print errors to log instead of returning.
- Remove special stats collectors
Users can continue to include the special stat collector as a separate app connecting to uplink through TCP with [this code](https://gist.github.com/de-sh/e2085eb2f28fa97eb712038b8b07ef20).
Certain glob related errors lead to uplink's built-in stat collector failing, which shouldn't be the case.
Run uplink with stat collector enabled on a device without files at the path described by `/sys/devices/virtual/thermal/thermal_zone*/temp`.
> fix: glob error stopping stat collector

- uplink/src/base/mod.rs
- uplink/src/lib.rs
Closes #
This will ensure that use of default config isn't hindered by change in platform, i.e. `/var/lib/` isn't accessible on windows/android.
```
░█░▒█░▄▀▀▄░█░░░▀░░█▀▀▄░█░▄
░█░▒█░█▄▄█░█░░░█▀░█░▒█░█▀▄
░░▀▀▀░█░░░░▀▀░▀▀▀░▀░░▀░▀░▀
version: 2.5.0
profile: debug
commit_sha: 7a4cb757110f5944ac2b821125f945617add1ff8
commit_date: 2023-07-27T08:34:04Z
project_id: demo
device_id: 1001
remote: stage.bytebeam.io:8883
persistence_path: /home/uplink/.persistence
secure_transport: true
max_packet_size: 256000
max_inflight_messages: 100
keep_alive_timeout: 30
```
> feat: use `current_dir` instead of `/var/lib`

- configs/config.toml
- uplink/src/base/bridge/mod.rs
- uplink/src/base/mod.rs
- uplink/src/collector/mod.rs
- uplink/src/collector/script_runner.rs
- uplink/src/lib.rs
Closes #
Script runner allows user to send custom scripts that are executed on the device with `sh`.
User needs to run a shell script quickly on the connected device.
1. Start uplink with appropriate config:
```
action_redirections = { "send_file" = "run_script" }
script_runner = [{ name = "run_script" }]
persistence_path = "/var/tmp/uplink"
[downloader]
actions = [{ name = "send_file" }]
path = "/var/tmp/uplink"
```
2. Trigger `send_file` action with following script:
```
#!/bin/sh
echo 'This works'
```
3. Observe the execution of script on device:
```
2023-06-28T16:02:57.835734Z  INFO uplink::collector::downloader: Downloading from https://firmware.stage.bytebeam.io/api/v1/file/b307b17e-d0ec-4e7e-8e60-beb243b45e41/artifact into /var/tmp/uplink/send_file/save.sh …
```
> feat: built-in script runner

- README.md
- configs/config.toml
- configs/simulator.toml
- configs/stress.toml
- docs/apps.md
- examples/demo.go
- examples/demo.py
- examples/demo.rs
- examples/rpi/updates/app_update/app_update.sh
- examples/rpi/updates/app_update_rollback/app_update_rollback.sh
- examples/rpi/updates/deb_update/deb_update.sh
- examples/rpi/updates/rootfs_update/rootfs_update.sh
- scripts/bridge.py
- scripts/config.toml
- scripts/startup.sh
- scripts/uplink.toml
- tools/simulator/Cargo.lock
- tools/utils/src/push_data.rs
- tools/utils/src/wait_and_send.rs
- uplink/src/base/mod.rs
Closes #
Users might not want to configure uplink to use a particular port by writing out a `config.toml`, instead uplink could auto-provision an app to accept connections on port 5050 when the user hasn't configured one as default behavior. This helps with quickstart usage of the uplink utility.
Why 5050? From [this list](https://en.m.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) we figured that 5050 is unofficially reserved by Yahoo messenger, which doesn't seem like a possibility to be included on the devices we will see uplink running on 😅 
Run uplink without config, check banner for the TCP port number it is provisioned on
> feat: default main on port 5050 if tcpapps unconfigured

- uplink/src/collector/downloader.rs
Closes #
When creating new downloader directories, create them with correct permissions since client apps need to access them.
> create new directories with correct permissions

- uplink/src/collector/downloader.rs
Closes #
Downloader retrying issues related to file-system, the actual file being empty, etc. doesn't make much sense, whereas when it is caused by something related to the HTTP client, retrying could help.
1. HTTP error:
```
2023-08-15T10:32:25.912726Z  INFO uplink::base::bridge: Action response = ActionResponse { action_id: "1411", device_id: None, sequence: 1, timestamp: 1692095545912, state: "Downloading", progress: 0, errors: [], done_response: None }
2023-08-15T10:34:36.865645Z ERROR uplink::collector::downloader: Download failed: error sending request for url (https://firmware.stage.bytebeam.io/api/v1/file/0dd74499-4d79-480b-9892-165497654281/artifact): error trying to connect: tcp connect error: Network is unreachable (os error 101)
2023-08-15T10:35:06.252073Z  WARN …
```
> fix: retry only `reqwest` errors

- uplink/src/collector/downloader.rs
Closes #
Downloader thread was not printing any loglines when it dies out due to recv errors, making it tough to debug
> fix: downloader thread error out without logline

- tools/simulator/Cargo.lock
- tools/simulator/Cargo.toml
- tools/simulator/src/data.rs
- tools/simulator/src/main.rs
Closes #
Readability and timely generation of messages is a problem as we are unnecessarily relying on hand written code to handle it when tokio has abstractions that can easily improve readability as well as effectively remove the time skew
Test against stage: [uplink.log](https://gist.github.com/de-sh/c92f536568cea98f930f77171c87d4bb)
As can be noted from the logs, delta between timestamp values are exactly the values expected:
```
>>> 1692540495482 - 1692540494482 
1000
>>> 1692540494732 - 1692540494482
250
>>> 1692540494582 - 1692540494482
100
>>> 1692540494732 - 1692540494482
250
```
> fix: spawn generators to remove time skew

- uplink/src/collector/tunshell.rs
- uplink/src/lib.rs
Closes #
- Rename `TunshellSession` to `TunshellClient`
- Create an error type
- Remove unused `_config` and `echo_stdout`
- Refactor code to improve readabilitiy
For maintainability
Start a tunshell session from stage:
```
2023-08-23T03:55:35.200529Z  INFO uplink::base::mqtt: Action = Action { device_id: None, action_id: "1457", kind: "process", name: "launch_shell", payload: "{\"encryption\":\"JKyD8e86uifeBdJdf6ZuLM\",\"relay\":\"eu.relay.tunshell.com\",\"session\":\"PyqjSk1RBHKax2Soh6OXPG\"}" }
2023-08-23T03:55:35.200776Z  INFO uplink::base::bridge: Received action: Action { device_id: None, action_id: "1457", kind: "process", name: "launch_shell", payload: "{\"encryption\":\"JKyD8e86uifeBdJdf6ZuLM\",\"relay\":\"eu.relay.tunshell.com\",\"session\":\"PyqjSk1RBHKax2Soh6OXPG\"}" } …
```
> refactor: `TunshellSession` ~> `TunshellClient`

- uplink/src/base/bridge/mod.rs
Closes #
Tests could fail if `current_dir` has unexpected files and if action-routing is broken due to looping connections.
Ran `cargo test`
> test: use `current_dir`, remove unused loop

- uplink/src/base/bridge/mod.rs
- uplink/src/base/bridge/stream.rs
- uplink/src/base/bridge/streams.rs
- uplink/src/lib.rs
Closes #
`ActionResponse` messages should be batched by `Bridge` and not handled separately.
Run against stage with simulator:
```
2023-09-05T14:09:44.706971Z TRACE uplink::base::bridge::streams: Initialized stream buffer for action_status
2023-09-05T14:09:46.708824Z DEBUG uplink::base::bridge: Flushing stream = action_status
2023-09-05T14:09:46.708889Z TRACE uplink::base::bridge::stream: Flushing stream name: action_status, topic: /tenants/demo/devices/1001/action/status
```
> refactor: remove use of separate stream for `action_status`

- uplink/src/collector/simulator/data.rs
- uplink/src/collector/simulator/mod.rs
Closes #
The `action_status` must be received and noted by bridge against `current_action` before being pushed to platform.
```
2023-09-09T07:23:36.638370Z  INFO uplink::collector::simulator: Successfully sent all action responses
2023-09-09T07:23:36.638535Z  INFO uplink::base::bridge: Action response = ActionResponse { action_id: "1604", sequence: 10, timestamp: 1694244216638, state: "Completed", progress: 100, errors: [], done_response: None }
```
> fix: simulator should send `action_status` to bridge as `ActionResponse`

- simulator.sh
Closes #
It's desirable to not persist simulated streams in-memory, which has the capability of triggering the pod running simulator to be OOMkilled
Run against wrong url for broker, triggering a connection issue, but keeping uplink alive to receive simulated data:
```
2023-09-09T09:16:08.393065Z  INFO uplink::base::serializer:              slow: batches = 11  errors = 0 lost = 10 disk_files = 0   write_memory = 0 B read_memory = 0 B
...
2023-09-09T09:20:38.393373Z  INFO uplink::base::serializer:              slow: batches = 135 errors = 0 lost = 114 disk_files = 0   write_memory = 25.09 kB read_memory = 0 B
```
It can be observed that lost segment count is increasing, but some data, specifically from the following streams do get written into associated memory buffer:
- …
> feat: don't persist simulated streams in-memory

- uplink/src/collector/process.rs
- uplink/src/lib.rs
Closes #
Run against stage with example `tools/lock`:
```
#!/bin/bash
echo "{ \"sequence\": 0, \"timestamp\": $(date +%s%N | cut -b1-13),\"action_id\": \"$1\", \"state\": \"Locked\", \"progress\": 100, \"errors\": [] }"
```
send action with `name = "lock"` and see the following logs:
```
2023-09-13T15:16:19.508475Z  INFO uplink::base::mqtt: Action = Action { action_id: "1738", kind: "process", name: "lock", payload: "{}" }
2023-09-13T15:16:19.508628Z  INFO uplink::base::bridge: Received action: Action { action_id: "1738", kind: "process", name: "lock", payload: "{}" }
2023-09-13T15:16:19.508686Z  INFO uplink::base::bridge: Action response = ActionResponse { action_id: "1738", sequence: 0, timestamp: 1694618179508, state: "Received", progress: 0, errors: [], done_response: None } …
```
> fix: timeout process as per config

- uplink/src/collector/downloader.rs
Closes #
Download behavior should support continuing downloads that were partially completed earlier.
Use [download_qa.sh](https://gist.github.com/de-sh/1bfa3c727c9dc9af77951e43d64e097b) to perform the network reset scenario required for circumstances where download must be restarted.
REFER
- [Logs of downloader running into failure and restarting](https://gist.github.com/de-sh/e8346d6d8aea55ed5e58f232d511f335#file-downloader-log-L49)
- Screenshot of md5sum run on file that was to be downloaded, compared against the file that ended up being downloaded:
> feat: try continuing partially downloaded files

- storage/src/lib.rs
- uplink/src/base/serializer/mod.rs
Closes #
- Name the storage with topic string
- Log in-memory storage being deleted on overflow, when file is deleted provide info on which stream it was storing data for, etc.
Logs should reflect information about which stream is being read and which file is being deleted, to help trace cause of data-loss. To be able to trace the cause of data-loss, these logs will provide better observability into the storage layer for users to figure out what is wrong with their config, i.e. a log saying "Persistence disabled for storage: /tenants/.../gps/..., deleting in-memory buffer" would be easier to read and understand than having to look at `serializer: lost = 1` and not be able to figure out which stream is losing data.
Use qa script for persistence and disable mqtts for a while, before …
> log: start/complete reading from persisted stream

- uplink/src/collector/downloader.rs
Closes #
Downloader retries should not be limited to 3 times, continuously retry till the download action is timedout
```
2023-10-10T16:59:01.368213Z  WARN uplink::collector::downloader: Retrying download; Continuing to download file from: bytes=0-33482
2023-10-10T16:59:01.369021Z ERROR uplink::collector::downloader: Download failed: error sending request for url (https://firmware.stage.bytebeam.io/api/v1/file/60e38118-4541-470a-a1cf-5901d9757da4/artifact): error trying to connect: tcp connect error: Connection refused (os error 111)
2023-10-10T16:59:02.371229Z  WARN uplink::collector::downloader: Retrying download; Continuing to download file from: bytes=0-33482
2023-10-10T16:59:02.371601Z ERROR uplink::collector::downloader: Download failed: error sending request for url …
```
> fix: continuous retry till timeout

- uplink/src/collector/downloader.rs
Closes #
on 32bit machines 99 * 571421193 overflows
```
fn main() {
let x = 571401090;
assert_eq!(dbg!(99.99 * x as f64 / 571421193 as f64) as u8, 99);
// let x = 571401090;
// assert_eq!(dbg!(99_usize * x / 571421193_usize) as u8, 99);
}
```
run against armv7 with `cross run --target=armv7-linux-androideabi`
> fix: usize multiplication overflow on 32bit machines

- Cargo.lock
- uplink/src/base/actions.rs
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/collector/downloader.rs
- uplink/src/collector/process.rs
- uplink/src/collector/script_runner.rs
- uplink/src/lib.rs
Closes #
To remove/cleanup unnecessary code for handling timeout from app side.
Run uplink as usual but with an action of extremely short duration, send an action that it is configured to handle, no change in uplink behavior observed. Action still timedout when not responded to and the app stopped processing action on timeout.
> refactor: remove timeout information from apps

- uplink/src/base/actions.rs
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/data_lane.rs
- uplink/src/base/bridge/mod.rs
- uplink/src/base/bridge/stream.rs
- uplink/src/base/bridge/streams.rs
Closes #
Clickhouse expects the field "id" to be the device_id and not the action_id, this fixes that clash in beamd which lead to loss of action_id information
```
2023-11-03T07:36:25.015854Z  INFO uplink::base::bridge::actions_lane: Action response = ActionResponse { action_id: "2183", sequence: 4, timestamp: 1698996985015, state: "Downloaded", progress: 100, errors: [], done_response: Some(Action { action_id: "2183", kind: "process", name: "update_firmware", payload: "{\"url\":\"https://firmware.stage.bytebeam.io/api/v1/firmwares/new firmware/artifact\",\"content_length\":12734,\"file_name\":\"new firmware\",\"download_path\":\"/var/tmp/ota/1/update_firmware/new firmware\"}", deadline: Some(Instant { tv_sec: 43865, tv_nsec: 161892981 }) }) }
[uplink/src/base/serializer/mod.rs:481] …
```
> fix: `ActionResponse.action_id` serialization

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/data_lane.rs
- uplink/src/base/bridge/stream.rs
- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/lib.rs
Closes #
Removes the steps of converting a number to a duration within the config, makes the code less verbose and hence more readable
> refactor: directly deserialize as `Duration`

- uplink/src/base/actions.rs
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/data_lane.rs
- uplink/src/base/bridge/stream.rs
- uplink/src/base/bridge/streams.rs
- uplink/src/collector/simulator/mod.rs
Closes #
We seek to send action responses onto two streams of the following form:
1. The original: `/tenants/{tenant_id}/devices/{device_id}/action/status`
2. The more action specific: `/tenants/{tenant_id}/devices/{device_id}/action_status/{stream_name}`
The action specific topics can hence forth be subscribed to receive notifications regarding progress of an action that is of interest.
```
2023-11-16T13:17:35.344081Z  INFO uplink::collector::simulator: Successfully sent all action responses
2023-11-16T13:17:35.344317Z  INFO uplink::base::bridge::actions_lane: Action response = ActionResponse { action_id: "2223", action_name: None, sequence: 10, timestamp: 1700140655344, state: "Completed", progress: 100, errors: [], done_response: None }
2023-11-16T13:17:35.344555Z DEBUG …
```
> feat: `action_status` on action specific stream

- uplink/src/base/serializer/mod.rs
Closes #
Added `reload_inflight` method to the serializer module which reads from disk and publishes packets back onto `EventLoop` and deletes the file.
Graceful shutdown requires graceful recovery on restart, which means we need to load publishes back from file.
Spinned up docker instance and used qa-scripts like `qa-scripts/persistence.sh` to test out the functionality.
```
2023-11-21T12:19:20.040174Z  INFO uplink::base::serializer: Switching to slow eventloop mode!!
2023-11-21T12:19:20.040229Z DEBUG uplink::base::mqtt: Writing pending publishes to disk: /var/tmp/persistence/inflight
2023-11-21T12:19:20.040599Z  INFO storage: Flushing data to disk for stoarge: /tenants/demo/devices/251/events/imu/jsonarray; path = "/var/tmp/persistence/imu/backup@0"
```
```
2023-11-21T12:34:54.530267Z …
```
> feat: load saved inflight publishes on uplink restart

- storage/src/lib.rs
- uplink/src/base/serializer/metrics.rs
- uplink/src/base/serializer/mod.rs
Closes #
Currently we only track count of files in disk and not the size of files
```
2023-12-05T13:13:25.332424Z  INFO uplink::base::serializer:           catchup: batches = 4481 errors = 0 lost = 401 disk_files = 1761 disk_utilized = 47.79 MB write_memory = 3.05 MB read_memory = 0 B
```
> feat: track disk space utilized by persistence

- storage/src/lib.rs
Closes #
Helps us reuse this code in #299 where currently there is a custom implementation of the same
Run QA persistence test, turn down the internet, bring it back up. Observed that things work as expected.
```
2023-12-08T11:05:29.590695Z  WARN storage: file limit reached. deleting backup@9; path = "/var/tmp/persistence/imu/backup@9"
2023-12-08T11:05:29.590750Z  INFO storage: Flushing data to disk for stoarge: /tenants/demo/devices/1001/events/imu/jsonarray; path = "/var/tmp/persistence/imu/backup@12"
2023-12-08T11:05:29.590944Z DEBUG uplink::base::serializer: Lost segment = 9
2023-12-08T11:05:34.441571Z  WARN storage: Persistence disabled for storage: /tenants/demo/devices/1001/events/bms/jsonarray. Deleted in-memory buffer on overflow
2023-12-08T11:05:34.441645Z DEBUG …
```
> refactor: handle files on disk as `PersistenceFile`

- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/data_lane.rs
- uplink/src/base/bridge/mod.rs
- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/collector/script_runner.rs
- uplink/src/console.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Will be used to send control messages to the various uplink components, currently this is limited to shutdown only
> refactor: `CtrlTx` to send control messages to various uplink components

- simulator.sh
Closes #
Fetching tenant ID from env variable - BYTEBEAM_TENANT_ID
Need to run simulator on non-demo tenanst for testing purpose
> feat: enable simulation on non-demo tenants

- uplink/src/base/serializer/metrics.rs
- uplink/src/base/serializer/mod.rs
Closes #
\
Improves observability into the serialization stage of uplink, helps customers determine if compression is helpful on a particular stream or not when paired along with #320.
```
1-09T19:04:06.379085Z  INFO uplink::base::serializer:               imu: serialized_data_size = 10.84 kB compressed_data_size = 7.96 kB avg_serialization_time = 62us avg_compression_time = 106us
2024-01-09T19:04:06.379102Z  INFO uplink::base::serializer:     device_shadow: serialized_data_size = 1.14 kB compressed_data_size = 1.14 kB avg_serialization_time = 32us avg_compression_time = 0us
2024-01-09T19:04:06.379110Z  INFO uplink::base::serializer:             motor: serialized_data_size = 24.73 kB compressed_data_size = 24.73 kB avg_serialization_time = 208us avg_compression_time = 0us …
```
> feat: Track serialization and compression times in nanos

- uplink/src/base/mod.rs
- uplink/src/base/monitor/mod.rs
- uplink/src/base/serializer/metrics.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/lib.rs
Closes #
- Collect and forward stream wise stats about compression sizes(before and after)(on a new stream)
- Configuration of the stream wise stats topic is now with `bridge_topic` and `serializer_topic` as these two modules now do the forwarding of stats on a stream wise basis, instead of being restricted to just the bridge.
- `DEFAULT_CONFIG` updated to reflect this. 
Allows customers to track data savings through compression. This only tracks data size in bytes, we could also track the time it takes to serialize/compress as that could also provide important information.
Tested against simulator with one stream compression turned on:
```
1-09T19:04:06.379085Z  INFO uplink::base::serializer:               imu: serialized_data_size = 10.84 kB compressed_data_size = 7.96 kB …
```
> feat: track stream-wise compression stats in serializer

- configs/config.toml
- examples/android/etc/uplink.config.toml
- qa-scripts/streams.sh
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/stream.rs
- uplink/src/base/bridge/streams.rs
- uplink/src/base/mod.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/lib.rs
Closes #
`buf_size` confused users, uses alias for backward compatability
Run uplink against configs with the following configs:
1. With buf_size:
```yaml
[streams.device_shadow]
...
buf_size = 1
```
```
2024-02-07T11:49:30.185770Z  INFO uplink::base::bridge::streams:        device_shadow: points = 10    batches = 10    latency = 4499
```
2. With batch_size:
```yaml
[streams.device_shadow]
...
buf_size = 2
```
```
2024-02-07T11:51:33.689721Z  INFO uplink::base::bridge::streams:        device_shadow: points = 10    batches = 5    latency = 4095
```
> style: `batch_size` clarification

- uplink/src/collector/systemstats.rs
Fixes [comment](https://github.com/bytebeamio/uplink/commit/3a2374c46f4166b307bc801e679c1e1fdb646883#commitcomment-131710329)
Calculations of network write/read bitrates was the averaged from startup value instead of being associated with only the previous few seconds, which changes with this fix.
1. https://docs.rs/sysinfo/latest/sysinfo/struct.Networks.html#method.refresh_list
2. https://docs.rs/sysinfo/latest/sysinfo/struct.Networks.html#method.refresh
3. https://docs.rs/sysinfo/latest/sysinfo/struct.NetworkData.html#method.total_received
4. https://docs.rs/sysinfo/latest/sysinfo/struct.NetworkData.html#method.received
> fix: calculate network for concerned period

- uplink/src/collector/downloader.rs
Closes #
Currently uplink retries all HTTP errors, even 4XX/5XX, with this we are forgoing this and expecting uplink to only retry a download when it fails due to issues like a disconnection
> fix: need not retry HTTP status errors

- uplink/src/base/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/lib.rs
Closes #
Reorganize the code to allow for handling restart events
To handle restart events performed between a download action which would otherwise have lead to a download being lost and action being timedout.
Kill uplink mid download, restart later, observe logs
> feat: restart download post reboot

- uplink/src/collector/downloader.rs
Closes #
Partially downloaded files clog up disk
Run download action with small timeout in config, but large file contents, use `tree` command to witness the file being created and delted as log line for deletion is also printed by uplink.
> fix: delete downloaded file on action timeout

- uplink/src/base/monitor/mod.rs
- uplink/src/base/serializer/metrics.rs
Closes #
Fractional part of time is missing on serialization
JS payload after change:
```js
{
"timestamp": 1715249644559,
"sequence": 13,
"stream": "bms",
"serialized_data_size": 133510,
"compressed_data_size": 133510,
"total_serialization_time": 0.022287279,
"avg_serialization_time": 0.001714406,
"total_compression_time": 0.0,
"avg_compression_time": 0.0
}
```
> fix: duration in seconds missing fractions

- uplink/src/collector/downloader.rs
Closes #
Download always fails post uplink restart due to lack of write permissions as file is opened read-only
1. Start uplink
2. Trigger download action
3. Restart uplink
4. Wait for action to complete (would have immediately failed earlier, but now succeeds)
> fix: bad file descriptor

- uplink/src/collector/downloader.rs
- uplink/src/console.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
There might be a requirement in the system to disable the downloader in order to prefer other network access events on the system that might otherwise be hindered by large downloads.
1. Start uplink
2. Trigger a download action, wait for the download to start on the device
3. Once the download has started, disable downloader with:
```sh
curl -X PUT http://localhost:3333/disable_downloader
```
4. Observe if download continues or if the timeout is short enough, for the action to be timedout.
5. After noticing that download is disabled as expected, enable downloader with:
```sh
curl -X PUT http://localhost:3333/enable_downloader
```
6. Wait for the download to complete as expected.
Observations:
```
2024-05-03T06:10:17.367319Z TRACE uplink::collector::downloader: Downloading: size = …
```
> feat: allow stoppage of downloader to free up network

- configs/config.toml
- uplink/src/base/actions.rs
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/collector/downloader.rs
- uplink/src/collector/process.rs
- uplink/src/collector/script_runner.rs
- uplink/src/config.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Action mid execution should be cancellable at one of two places:
1. During execution in a preemptable stage, e.g. while downloading a file(should also delete file created as a result of partial download)
2. At the end of a non-preemptable stage, e.g. at the end of a system-update, but before a restart sequence that would apply the update, this allows the customer to tunshell into the device and make any revertions necessary, but this is just an example and needs more thinking.
As an example of how this can be configured at the application level, downloader is the first built-in to support cancellation, as part of the cancellation procedure, it will also delete a partially downloaded file.
Awaiting backend support for testing
> feat: action cancellation

- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/main.rs
Closes #
- Uplink loses track of all action status when network is down and uplink restarts
- Uplink loses track of parallel actions on a restart
Start uplink and trigger a launch_shell, restart uplink before the action reaches 100% progress
> fix: mark parallel actions as failed on restart

- uplink/src/base/bridge/actions_lane.rs
Closes #
1. Marks cancellations as successful when action is failed, else marks it as successful
2. Adds tests for cancellation scenarios
NOTE: cancellation will be marked as successful even if action was failed by any other causes other than cancellation
> fix: action cancellation state loss

- tools/deserialize-backup/src/main.rs
> feat: write storage to human readable file

- configs/config.toml
- uplink/src/base/serializer/mod.rs
- uplink/src/config.rs
Closes #
This fixes unrestricted memory allocation in scenarios where multiple streams are created, each growing upto 10MB.
NOTE: if left unconfigured, default value will still be 10MB
> fix: configurable default backlog buffer size

- Cargo.lock
- configs/config.toml
- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/data_lane.rs
- uplink/src/base/bridge/streams.rs
- uplink/src/config.rs
Closes #
Streams limit is made configurable
NOTE: Pre-allocates size of stream map 
1. Ran uplink as usual with a `max_stream_count` unconfigured with 21 streams(including system stats streams), failed to accept 21st stream with:
```
[31mFailed to create "t12" stream. More than max 20 streams[0m
```
2. Ran uplink with `max_stream_count` configured to 40 with upto 30 data streams, no issues observed
3. Ran uplink with `max_stream_count` configured to 40 with upto 41 data streams:
```
[31mFailed to create "t42" stream. More than max 40 streams[0m
```
> fix: allow configuring `max_stream_count`

- configs/config.json
- uplink/src/main.rs
Closes #
`update_uplink_config`
Started uplink with both toml and json versions of config, both work exactly as expected.
1. Start uplink with config file without/unexpected extension:
```
Error: Auth file couldn't be loaded from "uplink.config"; supported file extensions: [`.json`,`.toml`]
```
2. Start uplink with `config.toml`/`config.json`, observed that behavior is the same no matter JSON or TOML but it works
> feat: support json uplink configs

- uplink/src/base/bridge/actions_lane.rs
Closes #
Restart uplink after corrupting the contents of persistence/current_action.
- Observed previously that the following log would be printed and the errors would be faced when trying to receive actions or send action updates.
```
[2m2024-10-09T14:47:22.615790Z[0m [31mERROR[0m [1;31muplink[0m[31m: [31mActions lane stopped!! Error = Serde error EOF while parsing a value at line 1 column 0[0m
```
- Observed after change that errors no longer occurred after the updated log saying:
```
[2m2024-10-09T20:57:62.215291Z[0m [31mERROR[0m [1;31muplink::base::actions_lane[0m[31m: [31mCouldn't load saved action: Serde error EOF while parsing a value at line 1 column 0[0m
```
> fix: ignore corrupted `current_action` file

- uplink/src/base/serializer/mod.rs
- uplink/src/lib.rs
- uplink/tests/serializer.rs
Closes #
Added a test to ensure working of serializer in FIFO order.
> refactor: use a wrapper to simplify interfacing with `storage`

- configs/config.toml
- uplink/src/base/serializer/mod.rs
- uplink/src/config.rs
- uplink/tests/serializer.rs
Closes #
[Design doc](https://docs.google.com/document/d/1P5L38mc9UgYeKn0ZyxQSXQGUJQr_OLTZRfq6bntz-mw/edit?usp=sharing)
When configured with the following configuration variable, serializer will push latest packet if it hasn't already before pushing older data in FIFO order from storage:
```toml
live_data_first = true
```
This will ensure that customers aren't frustrated by extremely slow data push, which makes it practically impossible to track the device.
Added test to ensure `Serializer` working is as expected.
> feat: `Serializer` pushes latest data first if configured to do so

- Dockerfile
- tools/utils/src/push_data.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/lib.rs
- uplink/tests/serializer.rs
Closes #
When pushing persisted data to broker, make sure that it is for the right tenant, otherwise drop it.
Persisted data can cause problems if device is reprovisioned.
* Tests in QA document
* Forced uplink to save data to persistence, stopped uplink, reprovisioned device, and restarted it. Uplink dropped stale data in persistence.
> fix: Ignore saved data for different tenant
