bytebeamio/uplink

- uplink/src/collector/systemstats.rs
> Run `refresh_memory()` to ensure `total_memory` is properly set

- uplink/src/base/actions/ota.rs
Comment out code associated download size and completion estimation. Ensures that frequency of ActionResponses are limited.
> Ensure lesser frequency of action responses

- .github/workflows/release.sh
- .github/workflows/release.yml
- .gitignore
Add `release.sh` to build for multiple targets with the help of cross
> Write build script

- Cargo.lock
- disk/src/lib.rs
- uplink/Cargo.toml
- uplink/src/base/actions/controller.rs
- uplink/src/base/actions/mod.rs
- uplink/src/base/actions/ota.rs
- uplink/src/base/actions/process.rs
- uplink/src/base/actions/tunshell.rs
- uplink/src/base/mod.rs
- uplink/src/base/mqtt.rs
- uplink/src/base/serializer.rs
- uplink/src/collector/simulator.rs
- uplink/src/collector/systemstats.rs
- uplink/src/collector/tcpjson.rs
- uplink/src/lib.rs
- uplink/src/main.rs
use `rumqttc v0.11`, `sysinfo v0.23` and fix cippy suggestions
> Update dependencies and clean-up code

- Cargo.lock
- tools/tunshell/Cargo.lock
- tools/tunshell/Cargo.toml
- tools/tunshell/src/main.rs
- uplink/Cargo.toml
- uplink/src/base/actions/tunshell.rs
* Fix tools/tunshell
* Pin tunshell version to latest master
* add some logging code
> make tools/tunshell work

- .github/workflows/release.yml
test run: https://github.com/henil/uplink-dev/releases/tag/v0.15.0
> ci(release): Added aarch musl and gnu build in release process

- uplink/src/lib.rs
Remove `RxTx`
Remove `RxTx`
To simplify the codebase
NA
> feat: remove `RxTx`

- configs/demo.toml
- paths/path0.json
- paths/path1.json
- paths/path2.json
- paths/path3.json
- paths/path4.json
- paths/path5.json
- paths/path6.json
- paths/path7.json
- paths/path8.json
- paths/path9.json
- uplink/src/collector/simulator.rs
Updates to simulator for operation on demo tenant with platform.
1. GPS paths had lat/lngs reversed, update the path files.
2. Update topic name and fields of peripheral state to be as is in demo on demo.
3. Update simulator config to simulate 50 devices.
> fix: Simulator updates

- Cargo.lock
- disk/Cargo.toml
- uplink/Cargo.toml
> chore: update deps and base rustc version

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/collector/systemstats.rs
Closes #
Use latest `sysinfo` crate to keep track of system component temperatures
> feat: update `sysinfo` and track component temperatures

- uplink/src/collector/systemstats.rs
Closes #
Collects and sets timestamp for stats at stat collection
Timestamp issue observed on platform
> fix: set timestamp at point of stat collection

- uplink/src/collector/tcpjson.rs
- uplink/src/collector/util.rs
Closes #57
Refactor out code relating to handling of data streams
`Stream` handling with `Streams`
Maintainability improvements
> feat: refactor with `Streams`

- uplink/src/base/mod.rs
- uplink/src/collector/logging/mod.rs
> feat: enable stream sizing for linux logs

- uplink/src/base/mod.rs
- uplink/src/base/serializer.rs
Closes #
Collect stream name from Package
> feat: stream name from `Package` in `Serializer`

- uplink/src/collector/mod.rs
- uplink/src/lib.rs
Closes #
Fixes compiling mac-os binary on release
> fix: compiling to non linux/android targets

- .github/workflows/release.yml
Closes #
Adds m1 mac as a target to release CI
> feat: compile binary for m1 mac on release

- uplink/src/base/serializer.rs
- uplink/src/base/serializer/metrics.rs
Closes #
DRY constructing of Publish packets, writing it to disk, etc.
To improve code readability, using DRY to bring moving parts closer together and help in understanding flow of data.
- Regular working of uplink,  observed to be successfully writing serializations to network and disk as expected.
> feat: refactor `serializer.rs` to improve readability

- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
Provide better detail about a missing file when starting uplink
> feat: detail missing file in error message

- uplink/src/collector/simulator.rs
Closes #
Improved code readability in simulator by using `DelayQueue`.
Improved readability, use of `DelayQueue` as an abstraction to remove unnecessary spreads of "scheduler" code.
Ran uplink in simulator mode on device to verify behavior.
> refactor: `DelayQueue` in sim improves readabilitiy

- uplink/src/collector/tcpjson.rs
> fix: log entire action

- uplink/src/base/mod.rs
- uplink/src/collector/util.rs
Closes #
Simplifies code and corrects log message to reflect actual meaning of stream status
For correctness and code maintainability
> fix: wrong log message and unnecessary complexity

- uplink/src/collector/downloader.rs
> Serde alias to DownloadFile

- uplink/src/base/bridge/bridge.rs
- uplink/src/base/bridge/mod.rs
- uplink/src/collector/downloader.rs
> fix:  tests broken by changes in `FileDownloader`

- uplink/src/base/bridge/bridge.rs
- uplink/src/collector/process.rs
- uplink/src/collector/systemstats.rs
- uplink/src/lib.rs
> feat: refactor `StatCollector` and `Process` with `BridgeTx`

- uplink/src/base/bridge/metrics.rs
- uplink/src/base/mqtt/metrics.rs
- uplink/src/base/mqtt/mod.rs
- uplink/src/base/serializer/metrics.rs
- uplink/src/base/serializer/serializer.rs
- uplink/src/collector/utils/streams.rs
> feat: rename `_count` fields

- disk/src/lib.rs
Closes #
Removes file from persistence only on being completely read from disk
Current behavior could lead to data loss as a result of uplink restarting serializer, and removing partially read file from disk.
Wrote test and confirmed behavior on device
> fix: don't remove file before finishing read

- .justfile
- configs/demo.toml
- configs/simulator.toml
- configs/toxic.json
- tools/noxious.sh
- uplink/src/base/serializer/metrics.rs
- uplink/src/base/serializer/serializer.rs
> Disk write errors

- simulator.sh
Closes #
Add step in simulator.sh to download device auth json files on start from bytebeam platform
To enable easy setup and working of simulator
Run as simulator against cloud and stage, verified connection and pushing on device_shadow
> fix: add step to download device auth file

- .github/workflows/rust.yml
- disk/src/lib.rs
- tools/utils/Cargo.lock
- uplink/src/apis.rs
- uplink/src/base/bridge/bridge.rs
- uplink/src/base/bridge/bridge_impl.rs
- uplink/src/base/bridge/mod.rs
- uplink/src/base/mqtt/metrics.rs
- uplink/src/base/mqtt/mod.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/base/serializer/serializer_impl.rs
- uplink/src/collector/simulator.rs
- uplink/src/collector/tcpjson.rs
- uplink/src/collector/utils/delaymap.rs
- uplink/src/collector/utils/streams.rs
- uplink/src/lib.rs
- uplink/src/main.rs
> feat: android ci

- Cargo.lock
- tools/tunshell/src/main.rs
- tools/utils/Cargo.lock
- uplink/Cargo.toml
- uplink/src/base/mod.rs
- uplink/src/collector/logging/journalctl.rs
- uplink/src/collector/logging/logcat.rs
- uplink/src/collector/logging/mod.rs
> * Combine journalctl and logcat config

- uplink/src/base/bridge/mod.rs
- uplink/src/base/mod.rs
- uplink/src/collector/logging/logcat.rs
- uplink/src/collector/systemstats.rs
- uplink/src/collector/tcpjson.rs
- uplink/src/lib.rs
- uplink/src/main.rs
https://linear.app/bytebeam/issue/PLAT-3744
* Rename stats config block to system_stats
* System stats bugfix
* Cleanup
> rename stats -> system_stats

- uplink/src/base/bridge/mod.rs
- uplink/src/collector/logging/mod.rs
- uplink/src/lib.rs
Closes #
LoggerInstance wasn't being launched anymore.
Tested that logs are being pushed and displayed on dashboard.
> fix: launch loggerinstance

- uplink/src/lib.rs
Closes #
Launch loggerinstance only on linux/android
> fix: compile on mac

- tools/utils/Cargo.lock
- uplink/src/collector/tcpjson.rs
> fix: use proper log levels

- tools/utils/src/push_data.rs
- uplink/src/collector/tcpjson.rs
> fix: clippy

- tools/utils/Cargo.lock
- uplink/src/collector/systemstats.rs
> fix: processor stats stream name

- uplink/src/base/actions.rs
- uplink/src/base/bridge/mod.rs
> fix: update action timeout when responses are received

- uplink/src/collector/tunshell.rs
Closes #
https://linear.app/bytebeam/issue/PLAT-3860
> fix: tunshell bugfix

- uplink/src/collector/tcpjson.rs
Closes #
Too much logs were being generated on exponent devices.
> fix: log minimal stuff at info level

- uplink/src/collector/downloader.rs
Closes #
Improve documentation to reflect current uplink system design
> doc: update downloader comments

- uplink/src/collector/logging/logcat.rs
> fix: duplicate timestamp key in serialized JSON

- uplink/src/collector/logging/logcat.rs
> "fix: revert #206, more testing needed"

- storage/src/lib.rs
Closes #
Conveys the behavior of persistence better
run cargo test to ensure behavior as per unit tests
```
$ cargo test
Compiling storage v0.1.0 (/home/devdutt/bytebeam/uplink/storage)
Finished test [optimized + debuginfo] target(s) in 0.55s
Running unittests src/lib.rs (/home/devdutt/bytebeam/uplink/target/debug/deps/storage-396b7a8f005a08db)
running 5 tests
test test::ensure_file_remove_on_read_completion_only ... ok
test test::flush_creates_new_file_after_size_limit ... ok
test test::reload_loads_correct_file_into_memory ... ok
test test::old_file_is_deleted_after_limit ... ok
test test::reload_loads_partially_written_write_buffer_correctly ... ok
test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
> refactor: use `VecDeque` for readability

- scripts/one_time_setup.sh
Closes #
Clean up one time setup script
> fix: Cleanup Code

- docs/apps.md
Closes #
apps.md has been deemed outdated
> doc: update apps.md

- uplink/src/collector/systemstats.rs
Closes #
Custom stat collector shouldn't be a part of the codebase as that leads to maintenance related problems.
> feat: remove specific extractors

- uplink/src/base/bridge/mod.rs
Closes #
To verify that uplink accepts other actions during tunshell session and vice-versa without blocking.
> test: verify tunshell action pass-through

- uplink/src/lib.rs
- uplink/src/main.rs
> feat: name threads when spawning

- examples/demo.cpp
Closes #
Add a CPP example
Tested by attaching to uplink
> cpp example

- Cargo.lock
- Cargo.toml
- storage/Cargo.toml
- storage/src/lib.rs
- tools/utils/Cargo.toml
- uplink/Cargo.toml
Closes #
Makes dependencies easier to manage between workspace projects
Run uplink as normal, with persistence QA setup, perform shutdown, observed normal operation
> chore: use workspace dependencies

- uplink/src/collector/log_reader.rs
> fix: allow word based months in timestamps

- uplink/src/base/bridge/mod.rs
- uplink/src/lib.rs
- uplink/src/main.rs
Closes #
To DRY channel creation surrounding action registration
> refactor: action registration

- uplink/src/base/actions.rs
> deprecate kind field in actions

- uplink/src/collector/downloader.rs
Closes #
When a download fails mid way, the error that caused it should be sent to platform so that we can log it for better observability.
Try a download with the download server down
> fix: forward error messages triggering retry

- uplink/src/collector/downloader.rs
> refactor: downloader

- uplink/src/collector/downloader.rs
Closes #
Downloader should not fail until it receives an error status response from server or action is timedout.
1. Start uplink
2. Trigger download action
3. Restart uplink but with network down
4. Observe network failure errors being logged
5. Bring network back up and notice download continuing
> fix: downloader retry on DNS at startup

- tools/deserialize-backup/src/main.rs
> fix: update deserialize utility

- simulator.sh
> Simulator: increased timeout

- uplink/src/base/bridge/actions_lane.rs
- uplink/src/base/bridge/data_lane.rs
- uplink/src/base/bridge/mod.rs
- uplink/src/base/bridge/streams.rs
- uplink/src/base/mqtt/mod.rs
- uplink/src/base/serializer/mod.rs
- uplink/src/collector/downloader.rs
- uplink/src/config.rs
- uplink/src/lib.rs
- uplink/src/main.rs
- uplink/tests/bridge.rs
- uplink/tests/downloader.rs
Closes #
Allows for persisting uplink config back into file on update
> refactor: separate out `DeviceConfig`

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/collector/journalctl.rs
- uplink/src/collector/logcat.rs
- uplink/src/config.rs
- uplink/src/main.rs
Closes #
Allows remotely updating uplink config, blocked on #356
> feat: `update_uplink_config`

- Dockerfile
> fix: simulator tools/* missing

- docs/quickstart.md
> chore: update docs

- Cargo.lock
- docs/quickstart.md
- tools/utils/Cargo.toml
- tools/utils/src/push_data.rs
> chore: update docs and mock data script

- tools/utils/src/push_data.rs
- uplink/src/base/mqtt/mod.rs
- uplink/src/base/serializer/mod.rs
> fix: apply tenant filter at the right place when reading persisted data

- uplink/src/main.rs
> fix: abort entire process if a panic occurs in any subtask

- uplink/Cargo.toml
> chore: version 2.18.2

- Cargo.lock
- uplink/Cargo.toml
- uplink/src/collector/systemstats.rs
* Calculate component temperature properly on android
* Deduplicate block devices
> fix: android system stats fixes
